#!/bin/bash

mkdir -p ./Build

g++ $(find ./* | grep .cpp)                 \
    $(find ./* | grep .hpp)                 \
    -w -std=c++0x -lm                       \
    `pkg-config --cflags --libs gtkmm-3.0`  \
    -o ./Build/AlGi_Crypt0r